#! /usr/bin/env python3

"""
Copyright (c) 2019 B. Zoltán Gorza
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the <organization> nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL B. ZOLTÁN GORZA BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

# IMPORTANT: this script was made for private use originally and never
#            meant to be released, so if it's ugly as hell, that's why.

import markdown
from markdown.extensions import Extension
from gfm import AutolinkExtension
#import codecs
from os import remove

TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<title>lipu lili pi toki pona</title>
<meta charset="utf-8">
<link type="text/css" rel="stylesheet" href="{css}">
</head>
<body>
{here}
</body>
</html>
"""
CSS = "own.css"
FILES = [
    "README.md", "../definitions.md", "../grammar.md", "../dictionary.md", "../informal.md"
]
TMPFILE = "tmp.md"


def open_file(filename):
    try:
        f = open(filename, "r", encoding="utf-8")
    except:
        print("File reading error, terminating process")
        return
    text = f.read()
    f.close()
    return text


def htmlize(filename, template=TEMPLATE, css=CSS):
    txt = open_file(filename)
    if txt:
        txt = markdown.markdown(
            txt,
            extensions=["toc", "extra", "sane_lists"],
            extension_configs = {
                "toc": {
                    "title": "",
                    "anchorlink": True,
                    "permalink": True,
                    "baselevel": 1
                }
            })
        txt = template.format(filename=filename,
                              here=txt,
                              css=css)
    return txt


if __name__ == "__main__":
    output = ""
    for f in FILES:
        try:
            file = open(f, "r", encoding="utf-8")
            output += file.read() + "\n\n"
            file.close()
        except FileNotFoundError as fe:
            print("The file " + f + " was not found in parent directory.")
    output = output[0] + output[1:].replace("\n#", "\n##")
    with open(TMPFILE, "w", encoding="utf-8") as f:
        f.write(output)
    input("shall we continue?")
    if (output):
        filename_out = "master.html"
        f = open(filename_out, "w", encoding="utf-8")
        f.write(htmlize(TMPFILE, TEMPLATE))
        f.close()
        #remove(TMPFILE)
        print(filename_out, "has been written just fine.")
        
    else:
        print("Pass a filename as argument to htmlize that.")

# pandoc -f html -t epub -o master.epub master.html
# pandoc -s master.html --pdf-engine=xelatex -t latex --variable margin-left=1.5cm --variable margin-right=1.5cm --variable margin-top=1.5cm --variable margin-bottom=1.5cm -o master.pdf

# I've spent 1 hugging hour trying to fix this, but I don't care anymore
# [WARNING] Missing character: There is no ɑ in font [lmmono10-regular]:!
# [WARNING] Missing character: There is no ɛ in font [lmmono10-regular]:!
# [WARNING] Missing character: There is no ɪ in font [lmmono10-regular]:!
# [WARNING] Missing character: There is no ʊ in font [lmmono10-regular]:!